### ISSUE TITLE
`hitData.hitObject` copy bug in `qbRT::box` 

### ISSUE THREAD

**Issue by RedSkittleFox** [QuantitativeBytes/qbRayTrace2#2]
A minor bug. The `qbRT::ObjectBase` instance is created instead of `qbRT::Box`. 

https://github.com/QuantitativeBytes/qbRayTrace2/blob/fb7aa9aadcc747eacea1e56ca4bd9c0702a092f4/qbRayTrace/qbPrimatives/box.cpp#L201

Please try out this sample code ([godbolt](https://redskittlefox.godbolt.org/z/xPYzK7EaW)).
```cpp
#include <iostream>
#include <memory>

struct base
{
    virtual ~base() {}
    virtual void foo() {std::cout << "base\n"; }    
};

struct derived : base
{
    void foo() {std::cout << "derived\n"; }
    
    std::shared_ptr<base> bad_copy()
    {
        // analogy to marked code line
        return std::make_shared<base>(*this); // this constructs base, not derived!
    }

    std::shared_ptr<base> copy()
    {
        // note: std::static_pointer_cast is optional here
        return std::static_pointer_cast<base>(std::make_shared<derived>(*this)); 
    }
};

int main()
{
    derived src;
    auto bad = src.bad_copy();
    auto good = src.copy();
    bad->foo(); // this prints base, we wanted derived!
    good->foo();
    return 0;
};
```

Possible solution to copy: use `std::enable_shared_from_this<T>` with `qbRT::Box` class.

https://github.com/QuantitativeBytes/qbRayTrace2/blob/fb7aa9aadcc747eacea1e56ca4bd9c0702a092f4/qbRayTrace/qbPrimatives/box.hpp#L41
becomes 
```cpp
class Box : public ObjectBase, public std::enable_shared_from_this<Box>
```
and aforementioned line becomes
```cpp
hitData.hitObject = this->shared_from_this();
```

**Comment by QuantitativeBytes** [comment]
Hi RedSkittleFox! 

Thank you very much pointing this out, you are quite right that the way it was done originally would result in a copy of ObjectBase. This wasn't actually a problem with the code so far, but is the kind of bug that could become a problem later. You're suggestion for using std::enable_shared_from_this was great, so thank you for that. I have decided to go with this approach and it seems to work very well.

Thanks again!

QB.
